spring.application.name=TacnaEnBici


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tacna_en_bici}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:sql}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=50MB

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# THYMELEAF
# ==========================================
spring.thymeleaf.cache=false

# ==========================================
# SERVIDOR
# ==========================================
# Render asigna un puerto dinámico. En local usará el 8080.
server.port=${PORT:8080}